apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: micro-demo
type: Opaque
data:
  # CHANGE ME. This is base64("inventorypass")
  POSTGRES_PASSWORD: aW52ZW50b3J5cGFzcw==
  # DATABASE_URL = postgres://inventory:<password>@postgres:5432/inventory
  # base64("postgres://inventory:inventorypass@postgres:5432/inventory")
  DATABASE_URL: cG9zdGdyZXM6Ly9pbnZlbnRvcnk6aW52ZW50b3J5cGFzc0Bwb3N0Z3Jlczo1NDMyL2ludmVudG9yeQ==
  # CHANGE ME. base64("dev-secret-change-me")
  JWT_SECRET: ZGV2LXNlY3JldC1jaGFuZ2UtbWU=
